openapi: 3.1.0
info:
  version: 1.0.0
  title: Money Guard App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Money Guard
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations about users.
  - name: Transactions
    description: Operations about transactions.
  - name: Categories
    description: Operations about categories.
  - name: Summary
    description: Operations about summary.
servers:
  - url: https://money-guard-backend-ulen.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml
    post:
      $ref: ../swagger/paths/transactions/post.yaml

  /transactions/{id}:
    patch:
      $ref: ../swagger/paths/transactions/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/transactions/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
