openapi: 3.1.0
info:
  version: 1.0.0
  title: Money Guard App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Money Guard
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations about users.
  - name: Transactions
    description: Operations about transactions.
  - name: Categories
    description: Operations about categories.
  - name: Summary
    description: Operations about summary.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
